/// Attribute score normalization — v9 rank-aware per-face mapping.
///
/// Maps raw attribute scores (from `deriveAttributeScores`) to a user-facing
/// 5.0–10.0 range by blending:
///   - **global percentile** (calibration CDF → cross-user comparability)
///   - **within-face rank** (enforces ≥3.0 spread between top and bottom attr)
///
/// Quantile tables are generated by `test/calibration_test.dart` which runs
/// Monte Carlo through the real pipeline. Re-run after any weight/rule change.
library;

import 'package:face_reader/data/enums/attribute.dart';
import 'package:face_reader/data/enums/gender.dart';

// ──────────────────── Quantile Tables ────────────────────
//
// 21 points per attribute (p0, p5, …, p100). Values are raw-score quantiles
// from Monte Carlo over the hierarchical engine with N(0.2, 0.85) metric z
// inputs. Regenerate via `flutter test test/calibration_test.dart`.

const _attrQuantilesMale = <Attribute, List<double>>{
  Attribute.wealth: [-1.868, -0.670, -0.503, -0.394, -0.298, -0.221, -0.150, -0.078, -0.011, 0.053, 0.117, 0.188, 0.258, 0.338, 0.424, 0.526, 0.642, 0.776, 0.960, 1.269, 6.047],
  Attribute.leadership: [-2.382, -1.018, -0.725, -0.501, -0.363, -0.270, -0.191, -0.123, -0.057, 0.004, 0.063, 0.124, 0.188, 0.265, 0.360, 0.501, 0.790, 1.093, 1.382, 2.392, 10.876],
  Attribute.intelligence: [-1.055, -0.382, -0.280, -0.214, -0.160, -0.113, -0.072, -0.029, 0.010, 0.047, 0.087, 0.125, 0.165, 0.207, 0.254, 0.307, 0.372, 0.457, 0.606, 1.040, 6.007],
  Attribute.sociability: [-1.557, -0.396, -0.295, -0.226, -0.176, -0.130, -0.086, -0.048, -0.010, 0.030, 0.068, 0.106, 0.146, 0.189, 0.234, 0.283, 0.342, 0.409, 0.509, 0.673, 3.461],
  Attribute.emotionality: [-0.809, -0.266, -0.182, -0.123, -0.072, -0.030, 0.010, 0.047, 0.081, 0.115, 0.150, 0.185, 0.225, 0.262, 0.302, 0.347, 0.400, 0.463, 0.544, 0.668, 2.219],
  Attribute.stability: [-2.538, -0.803, -0.563, -0.417, -0.305, -0.210, -0.129, -0.053, 0.011, 0.074, 0.134, 0.193, 0.252, 0.318, 0.389, 0.465, 0.563, 0.683, 0.850, 1.134, 4.146],
  Attribute.sensuality: [-0.968, -0.404, -0.301, -0.227, -0.172, -0.122, -0.077, -0.036, 0.003, 0.045, 0.086, 0.132, 0.176, 0.222, 0.275, 0.344, 0.433, 0.566, 0.770, 1.013, 2.622],
  Attribute.trustworthiness: [-1.600, -0.488, -0.355, -0.270, -0.199, -0.139, -0.086, -0.037, 0.010, 0.055, 0.103, 0.149, 0.193, 0.242, 0.296, 0.366, 0.496, 0.751, 0.932, 1.132, 2.801],
  Attribute.attractiveness: [-1.279, -0.369, -0.249, -0.168, -0.108, -0.058, -0.012, 0.026, 0.061, 0.097, 0.129, 0.163, 0.197, 0.233, 0.269, 0.312, 0.373, 0.626, 1.876, 2.004, 4.580],
  Attribute.libido: [-1.467, -0.464, -0.360, -0.289, -0.233, -0.182, -0.137, -0.096, -0.055, -0.015, 0.026, 0.067, 0.110, 0.157, 0.209, 0.271, 0.351, 0.495, 1.517, 1.804, 3.521],
};

const _attrQuantilesFemale = <Attribute, List<double>>{
  Attribute.wealth: [-1.765, -0.607, -0.458, -0.358, -0.270, -0.198, -0.132, -0.069, -0.007, 0.053, 0.115, 0.176, 0.247, 0.321, 0.407, 0.506, 0.619, 0.746, 0.921, 1.236, 5.993],
  Attribute.leadership: [-2.255, -0.977, -0.694, -0.471, -0.335, -0.248, -0.179, -0.114, -0.053, 0.002, 0.061, 0.116, 0.179, 0.248, 0.340, 0.479, 0.771, 1.062, 1.329, 2.353, 10.892],
  Attribute.intelligence: [-1.055, -0.382, -0.280, -0.214, -0.160, -0.113, -0.072, -0.029, 0.010, 0.047, 0.087, 0.125, 0.165, 0.207, 0.254, 0.307, 0.372, 0.457, 0.606, 1.040, 6.007],
  Attribute.sociability: [-1.557, -0.396, -0.295, -0.226, -0.176, -0.130, -0.086, -0.048, -0.010, 0.030, 0.068, 0.106, 0.146, 0.189, 0.234, 0.283, 0.342, 0.409, 0.509, 0.673, 3.461],
  Attribute.emotionality: [-0.809, -0.266, -0.182, -0.123, -0.072, -0.030, 0.010, 0.047, 0.081, 0.115, 0.150, 0.185, 0.225, 0.262, 0.302, 0.347, 0.400, 0.463, 0.544, 0.668, 2.219],
  Attribute.stability: [-2.538, -0.803, -0.563, -0.417, -0.305, -0.210, -0.129, -0.053, 0.011, 0.074, 0.134, 0.193, 0.252, 0.318, 0.389, 0.465, 0.563, 0.683, 0.850, 1.134, 4.146],
  Attribute.sensuality: [-0.989, -0.407, -0.299, -0.225, -0.170, -0.124, -0.078, -0.036, 0.006, 0.046, 0.089, 0.131, 0.177, 0.225, 0.278, 0.344, 0.436, 0.565, 0.769, 1.006, 2.535],
  Attribute.trustworthiness: [-1.600, -0.488, -0.355, -0.270, -0.199, -0.139, -0.086, -0.037, 0.010, 0.055, 0.103, 0.149, 0.193, 0.242, 0.296, 0.366, 0.496, 0.751, 0.932, 1.132, 2.801],
  Attribute.attractiveness: [-1.279, -0.369, -0.249, -0.168, -0.108, -0.058, -0.012, 0.026, 0.061, 0.097, 0.129, 0.163, 0.197, 0.233, 0.269, 0.312, 0.373, 0.626, 1.876, 2.004, 4.580],
  Attribute.libido: [-1.423, -0.443, -0.341, -0.275, -0.220, -0.176, -0.133, -0.092, -0.055, -0.015, 0.023, 0.061, 0.102, 0.147, 0.195, 0.254, 0.333, 0.469, 1.534, 1.811, 3.519],
};

/// raw → empirical percentile (0..1) by linear interp between quantile points.
double _rawToPercentile(double raw, Attribute attr, Gender gender) {
  final q = gender == Gender.male
      ? _attrQuantilesMale[attr]!
      : _attrQuantilesFemale[attr]!;
  if (raw <= q[0]) return 0.0;
  if (raw >= q[20]) return 1.0;
  for (int i = 0; i < 20; i++) {
    final lo = q[i];
    final hi = q[i + 1];
    if (raw <= hi) {
      final span = hi - lo;
      final t = span > 0 ? (raw - lo) / span : 0.0;
      return (i + t) / 20.0;
    }
  }
  return 1.0;
}

/// Blend: 40% within-face rank (spread) + 60% global percentile (absolute level).
///
/// 2026-04-18 튜닝: face/ear 제외 9-노드 매트릭스 + shape preset + 상관 MC
/// 재보정 후, calibration accuracy 가 올라간 상태. rank 비중을 줄여 global
/// fidelity 를 높여야 실사용자 raw 가 속성간 비율 그대로 반영된다. 기존 60/40
/// 은 artificial spread 가 과해 매력도·신뢰도가 강제로 서열화되는 부작용이
/// 있었음.
const double _rankWeight = 0.40;
const double _globalWeight = 0.60;

/// Normalizes 10 attribute raw scores into 5.0–10.0. Guarantees:
///   - top attribute ≥ 8.0
///   - bottom attribute ≤ 7.0
///   - spread between top and bottom ≥ 3.0
Map<Attribute, double> normalizeAllScores(
    Map<Attribute, double> rawScores, Gender gender) {
  final globalPct = <Attribute, double>{};
  for (final entry in rawScores.entries) {
    globalPct[entry.key] = _rawToPercentile(entry.value, entry.key, gender);
  }

  // Rank by global percentile so all attributes share a 0..1 scale
  // regardless of raw-score magnitudes.
  final sorted = globalPct.entries.toList()
    ..sort((a, b) => b.value.compareTo(a.value));
  final ranks = <Attribute, int>{};
  for (int i = 0; i < sorted.length; i++) {
    ranks[sorted[i].key] = i;
  }
  final denom = (sorted.length - 1).toDouble();

  final result = <Attribute, double>{};
  for (final attr in Attribute.values) {
    final rankPct = (denom - ranks[attr]!) / denom;
    final gPct = globalPct[attr]!;
    final blended = _rankWeight * rankPct + _globalWeight * gPct;
    final score = 5.0 + blended * 5.0;
    result[attr] = (score * 10).round() / 10.0;
  }
  return result;
}

/// Single-attribute normalization — used by partial flows (compat engine)
/// that can't run the full 10-attribute rank step.
double normalizeScore(double raw, Attribute attr, Gender gender) {
  final pct = _rawToPercentile(raw, attr, gender);
  final score = 5.0 + pct * 5.0;
  return (score * 10).round() / 10.0;
}
