/// Attribute score normalization — v9 rank-aware per-face mapping.
///
/// Maps raw attribute scores (from `deriveAttributeScores`) to a user-facing
/// 5.0–10.0 range by blending:
///   - **global percentile** (calibration CDF → cross-user comparability)
///   - **within-face rank** (enforces ≥3.0 spread between top and bottom attr)
///
/// Quantile tables are generated by `test/calibration_test.dart` which runs
/// Monte Carlo through the real pipeline. Re-run after any weight/rule change.
library;

import 'package:face_reader/data/enums/attribute.dart';
import 'package:face_reader/data/enums/gender.dart';

// ──────────────────── Quantile Tables ────────────────────
//
// 21 points per attribute (p0, p5, …, p100). Values are raw-score quantiles
// from Monte Carlo over the hierarchical engine with N(0.2, 0.85) metric z
// inputs. Regenerate via `flutter test test/calibration_test.dart`.

const _attrQuantilesMale = <Attribute, List<double>>{
  Attribute.wealth: [-0.781, -0.303, -0.209, -0.139, -0.083, -0.034, 0.011, 0.056, 0.100, 0.146, 0.196, 0.252, 0.312, 0.378, 0.445, 0.525, 0.615, 0.711, 0.832, 1.029, 2.303],
  Attribute.leadership: [-1.287, -0.670, -0.458, -0.297, -0.202, -0.135, -0.080, -0.028, 0.021, 0.070, 0.120, 0.174, 0.238, 0.314, 0.398, 0.495, 0.599, 0.709, 0.846, 1.093, 3.207],
  Attribute.intelligence: [-0.814, -0.269, -0.189, -0.135, -0.088, -0.048, -0.011, 0.022, 0.054, 0.087, 0.119, 0.154, 0.189, 0.227, 0.271, 0.321, 0.384, 0.473, 0.651, 1.066, 3.288],
  Attribute.sociability: [-0.692, -0.263, -0.183, -0.126, -0.082, -0.040, -0.004, 0.030, 0.064, 0.097, 0.131, 0.168, 0.202, 0.240, 0.281, 0.324, 0.374, 0.436, 0.516, 0.642, 1.485],
  Attribute.emotionality: [-0.683, -0.178, -0.098, -0.037, 0.012, 0.054, 0.091, 0.128, 0.162, 0.197, 0.230, 0.266, 0.303, 0.340, 0.380, 0.423, 0.472, 0.530, 0.607, 0.722, 1.546],
  Attribute.stability: [-1.450, -0.630, -0.464, -0.345, -0.254, -0.179, -0.110, -0.051, 0.006, 0.057, 0.106, 0.154, 0.202, 0.258, 0.315, 0.379, 0.452, 0.529, 0.623, 0.768, 1.691],
  Attribute.sensuality: [-0.760, -0.279, -0.200, -0.146, -0.102, -0.063, -0.029, 0.004, 0.034, 0.066, 0.095, 0.127, 0.159, 0.193, 0.228, 0.266, 0.315, 0.374, 0.463, 0.631, 1.641],
  Attribute.trustworthiness: [-0.841, -0.338, -0.246, -0.182, -0.131, -0.085, -0.045, -0.003, 0.034, 0.070, 0.108, 0.144, 0.182, 0.227, 0.280, 0.341, 0.420, 0.523, 0.655, 0.813, 1.628],
  Attribute.attractiveness: [-0.696, -0.248, -0.169, -0.114, -0.070, -0.034, -0.001, 0.030, 0.058, 0.086, 0.113, 0.142, 0.168, 0.197, 0.229, 0.265, 0.307, 0.355, 0.425, 0.610, 1.900],
  Attribute.libido: [-0.923, -0.405, -0.310, -0.250, -0.202, -0.162, -0.124, -0.089, -0.054, -0.019, 0.016, 0.050, 0.089, 0.129, 0.178, 0.238, 0.327, 0.495, 0.670, 0.824, 1.901],
};

const _attrQuantilesFemale = <Attribute, List<double>>{
  Attribute.wealth: [-0.775, -0.287, -0.198, -0.132, -0.079, -0.031, 0.013, 0.055, 0.098, 0.143, 0.193, 0.245, 0.308, 0.377, 0.448, 0.524, 0.613, 0.705, 0.828, 1.025, 2.230],
  Attribute.leadership: [-1.277, -0.676, -0.458, -0.298, -0.206, -0.137, -0.083, -0.029, 0.020, 0.068, 0.121, 0.179, 0.244, 0.317, 0.404, 0.496, 0.596, 0.705, 0.844, 1.097, 3.115],
  Attribute.intelligence: [-0.814, -0.269, -0.189, -0.135, -0.088, -0.048, -0.011, 0.022, 0.054, 0.087, 0.119, 0.154, 0.189, 0.227, 0.271, 0.321, 0.384, 0.473, 0.651, 1.066, 3.288],
  Attribute.sociability: [-0.692, -0.263, -0.183, -0.126, -0.082, -0.040, -0.004, 0.030, 0.064, 0.097, 0.131, 0.168, 0.202, 0.240, 0.281, 0.324, 0.374, 0.436, 0.516, 0.642, 1.485],
  Attribute.emotionality: [-0.683, -0.195, -0.113, -0.052, -0.005, 0.037, 0.076, 0.112, 0.147, 0.180, 0.214, 0.249, 0.286, 0.323, 0.363, 0.408, 0.456, 0.515, 0.593, 0.705, 1.530],
  Attribute.stability: [-1.450, -0.630, -0.464, -0.345, -0.254, -0.179, -0.110, -0.051, 0.006, 0.057, 0.106, 0.154, 0.202, 0.258, 0.315, 0.379, 0.452, 0.529, 0.623, 0.768, 1.691],
  Attribute.sensuality: [-0.730, -0.287, -0.215, -0.164, -0.122, -0.085, -0.052, -0.021, 0.008, 0.036, 0.065, 0.095, 0.126, 0.158, 0.192, 0.231, 0.276, 0.331, 0.414, 0.569, 1.588],
  Attribute.trustworthiness: [-0.841, -0.338, -0.246, -0.182, -0.131, -0.085, -0.045, -0.003, 0.034, 0.070, 0.108, 0.144, 0.182, 0.227, 0.280, 0.341, 0.420, 0.523, 0.655, 0.813, 1.628],
  Attribute.attractiveness: [-0.746, -0.270, -0.183, -0.127, -0.084, -0.043, -0.009, 0.022, 0.053, 0.081, 0.109, 0.139, 0.169, 0.201, 0.235, 0.271, 0.316, 0.368, 0.448, 0.655, 2.023],
  Attribute.libido: [-0.877, -0.403, -0.309, -0.250, -0.202, -0.162, -0.123, -0.088, -0.054, -0.020, 0.014, 0.050, 0.089, 0.131, 0.179, 0.237, 0.331, 0.496, 0.674, 0.826, 1.946],
};

/// raw → empirical percentile (0..1) by linear interp between quantile points.
double _rawToPercentile(double raw, Attribute attr, Gender gender) {
  final q = gender == Gender.male
      ? _attrQuantilesMale[attr]!
      : _attrQuantilesFemale[attr]!;
  if (raw <= q[0]) return 0.0;
  if (raw >= q[20]) return 1.0;
  for (int i = 0; i < 20; i++) {
    final lo = q[i];
    final hi = q[i + 1];
    if (raw <= hi) {
      final span = hi - lo;
      final t = span > 0 ? (raw - lo) / span : 0.0;
      return (i + t) / 20.0;
    }
  }
  return 1.0;
}

/// Blend: 35% within-face rank (spread) + 65% global percentile.
///
/// 2026-04-19 v2.7: MC sampler bias 를 0.0 → 0.2 로 맞추면서 quantile CDF 가
/// realistic 분포와 일치. rank 비중은 spread invariant 보장 위해 보유.
const double _rankWeight = 0.35;
const double _globalWeight = 0.65;

/// Normalizes 10 attribute raw scores into 5.0–10.0. Guarantees:
///   - top attribute ≥ 8.0
///   - bottom attribute ≤ 7.0
///   - spread between top and bottom ≥ 3.0
Map<Attribute, double> normalizeAllScores(
    Map<Attribute, double> rawScores, Gender gender) {
  final globalPct = <Attribute, double>{};
  for (final entry in rawScores.entries) {
    globalPct[entry.key] = _rawToPercentile(entry.value, entry.key, gender);
  }

  // Rank by global percentile so all attributes share a 0..1 scale
  // regardless of raw-score magnitudes.
  final sorted = globalPct.entries.toList()
    ..sort((a, b) => b.value.compareTo(a.value));
  final ranks = <Attribute, int>{};
  for (int i = 0; i < sorted.length; i++) {
    ranks[sorted[i].key] = i;
  }
  final denom = (sorted.length - 1).toDouble();

  final result = <Attribute, double>{};
  for (final attr in Attribute.values) {
    final rankPct = (denom - ranks[attr]!) / denom;
    final gPct = globalPct[attr]!;
    final blended = _rankWeight * rankPct + _globalWeight * gPct;
    final score = 5.0 + blended * 5.0;
    result[attr] = (score * 10).round() / 10.0;
  }
  return result;
}

/// Single-attribute normalization — used by partial flows
/// that can't run the full 10-attribute rank step.
double normalizeScore(double raw, Attribute attr, Gender gender) {
  final pct = _rawToPercentile(raw, attr, gender);
  final score = 5.0 + pct * 5.0;
  return (score * 10).round() / 10.0;
}
