/// Attribute score normalization — v9 rank-aware per-face mapping.
///
/// Maps raw attribute scores (from `deriveAttributeScores`) to a user-facing
/// 5.0–10.0 range by blending:
///   - **global percentile** (calibration CDF → cross-user comparability)
///   - **within-face rank** (enforces ≥3.0 spread between top and bottom attr)
///
/// Quantile tables are generated by `test/calibration_test.dart` which runs
/// Monte Carlo through the real pipeline. Re-run after any weight/rule change.
library;

import 'package:face_reader/data/enums/attribute.dart';
import 'package:face_reader/data/enums/gender.dart';

// ──────────────────── Quantile Tables ────────────────────
//
// 21 points per attribute (p0, p5, …, p100). Values are raw-score quantiles
// from Monte Carlo over the hierarchical engine with N(0.2, 0.85) metric z
// inputs. Regenerate via `flutter test test/calibration_test.dart`.

const _attrQuantilesMale = <Attribute, List<double>>{
  Attribute.wealth: [-1.570, -0.365, -0.210, -0.104, -0.017, 0.060, 0.135, 0.206, 0.272, 0.334, 0.398, 0.464, 0.532, 0.608, 0.687, 0.774, 0.868, 0.980, 1.136, 1.419, 5.645],
  Attribute.leadership: [-1.697, -0.565, -0.304, -0.162, -0.073, 0.002, 0.068, 0.130, 0.188, 0.244, 0.303, 0.362, 0.431, 0.511, 0.639, 0.894, 1.114, 1.290, 1.477, 1.873, 5.652],
  Attribute.intelligence: [-0.660, -0.151, -0.065, -0.002, 0.046, 0.089, 0.127, 0.160, 0.195, 0.230, 0.265, 0.300, 0.337, 0.377, 0.420, 0.473, 0.540, 0.629, 0.774, 1.106, 4.883],
  Attribute.sociability: [-1.324, -0.280, -0.180, -0.103, -0.038, 0.018, 0.074, 0.125, 0.172, 0.221, 0.269, 0.317, 0.365, 0.417, 0.473, 0.532, 0.601, 0.678, 0.778, 0.942, 3.523],
  Attribute.emotionality: [-0.732, -0.110, -0.022, 0.042, 0.093, 0.137, 0.174, 0.210, 0.245, 0.279, 0.315, 0.350, 0.385, 0.426, 0.467, 0.514, 0.577, 0.653, 0.763, 0.961, 2.409],
  Attribute.stability: [-1.231, -0.015, 0.188, 0.343, 0.509, 0.685, 0.849, 1.019, 1.183, 1.316, 1.426, 1.516, 1.605, 1.690, 1.777, 1.883, 2.005, 2.137, 2.293, 2.543, 4.957],
  Attribute.sensuality: [-0.920, -0.246, -0.142, -0.070, -0.013, 0.036, 0.081, 0.121, 0.162, 0.202, 0.240, 0.281, 0.325, 0.373, 0.426, 0.487, 0.568, 0.714, 1.079, 1.410, 3.007],
  Attribute.trustworthiness: [-0.972, 0.035, 0.188, 0.309, 0.409, 0.510, 0.606, 0.696, 0.788, 0.874, 0.949, 1.017, 1.081, 1.145, 1.208, 1.274, 1.346, 1.425, 1.531, 1.690, 2.749],
  Attribute.attractiveness: [-0.980, -0.278, -0.158, -0.067, -0.002, 0.053, 0.107, 0.155, 0.202, 0.249, 0.293, 0.336, 0.380, 0.423, 0.467, 0.517, 0.569, 0.626, 0.700, 0.821, 2.828],
  Attribute.libido: [-1.378, -0.577, -0.441, -0.350, -0.279, -0.217, -0.161, -0.111, -0.062, -0.015, 0.030, 0.078, 0.129, 0.178, 0.236, 0.297, 0.368, 0.471, 0.997, 2.105, 4.638],
};

const _attrQuantilesFemale = <Attribute, List<double>>{
  Attribute.wealth: [-1.236, -0.296, -0.164, -0.066, 0.008, 0.078, 0.148, 0.209, 0.272, 0.332, 0.393, 0.454, 0.525, 0.598, 0.669, 0.750, 0.843, 0.953, 1.101, 1.375, 5.641],
  Attribute.leadership: [-1.636, -0.578, -0.306, -0.169, -0.082, -0.010, 0.055, 0.113, 0.170, 0.225, 0.280, 0.339, 0.405, 0.483, 0.609, 0.882, 1.097, 1.262, 1.442, 1.832, 5.527],
  Attribute.intelligence: [-0.660, -0.151, -0.065, -0.002, 0.046, 0.089, 0.127, 0.160, 0.195, 0.230, 0.265, 0.300, 0.337, 0.377, 0.420, 0.473, 0.540, 0.629, 0.774, 1.106, 4.883],
  Attribute.sociability: [-1.324, -0.280, -0.180, -0.103, -0.038, 0.018, 0.074, 0.125, 0.172, 0.221, 0.269, 0.317, 0.365, 0.417, 0.473, 0.532, 0.601, 0.678, 0.778, 0.942, 3.523],
  Attribute.emotionality: [-0.732, -0.110, -0.022, 0.042, 0.093, 0.137, 0.174, 0.210, 0.245, 0.279, 0.315, 0.350, 0.385, 0.426, 0.467, 0.514, 0.577, 0.653, 0.763, 0.961, 2.409],
  Attribute.stability: [-1.231, -0.015, 0.188, 0.343, 0.509, 0.685, 0.849, 1.019, 1.183, 1.316, 1.426, 1.516, 1.605, 1.690, 1.777, 1.883, 2.005, 2.137, 2.293, 2.543, 4.957],
  Attribute.sensuality: [-0.890, -0.233, -0.128, -0.060, -0.004, 0.045, 0.089, 0.128, 0.166, 0.202, 0.242, 0.280, 0.324, 0.368, 0.421, 0.480, 0.560, 0.703, 1.078, 1.382, 3.027],
  Attribute.trustworthiness: [-0.972, 0.035, 0.188, 0.309, 0.409, 0.510, 0.606, 0.696, 0.788, 0.874, 0.949, 1.017, 1.081, 1.145, 1.208, 1.274, 1.346, 1.425, 1.531, 1.690, 2.749],
  Attribute.attractiveness: [-1.046, -0.299, -0.165, -0.068, 0.003, 0.064, 0.119, 0.170, 0.219, 0.269, 0.317, 0.363, 0.410, 0.456, 0.506, 0.561, 0.617, 0.684, 0.760, 0.880, 2.919],
  Attribute.libido: [-1.409, -0.568, -0.431, -0.335, -0.265, -0.203, -0.143, -0.093, -0.044, 0.007, 0.053, 0.099, 0.149, 0.202, 0.259, 0.323, 0.398, 0.505, 1.033, 2.120, 4.638],
};

/// raw → empirical percentile (0..1) by linear interp between quantile points.
double _rawToPercentile(double raw, Attribute attr, Gender gender) {
  final q = gender == Gender.male
      ? _attrQuantilesMale[attr]!
      : _attrQuantilesFemale[attr]!;
  if (raw <= q[0]) return 0.0;
  if (raw >= q[20]) return 1.0;
  for (int i = 0; i < 20; i++) {
    final lo = q[i];
    final hi = q[i + 1];
    if (raw <= hi) {
      final span = hi - lo;
      final t = span > 0 ? (raw - lo) / span : 0.0;
      return (i + t) / 20.0;
    }
  }
  return 1.0;
}

/// Blend: 60% within-face rank (spread) + 40% global percentile (absolute level).
const double _rankWeight = 0.60;
const double _globalWeight = 0.40;

/// Normalizes 10 attribute raw scores into 5.0–10.0. Guarantees:
///   - top attribute ≥ 8.0
///   - bottom attribute ≤ 7.0
///   - spread between top and bottom ≥ 3.0
Map<Attribute, double> normalizeAllScores(
    Map<Attribute, double> rawScores, Gender gender) {
  final globalPct = <Attribute, double>{};
  for (final entry in rawScores.entries) {
    globalPct[entry.key] = _rawToPercentile(entry.value, entry.key, gender);
  }

  // Rank by global percentile so all attributes share a 0..1 scale
  // regardless of raw-score magnitudes.
  final sorted = globalPct.entries.toList()
    ..sort((a, b) => b.value.compareTo(a.value));
  final ranks = <Attribute, int>{};
  for (int i = 0; i < sorted.length; i++) {
    ranks[sorted[i].key] = i;
  }
  final denom = (sorted.length - 1).toDouble();

  final result = <Attribute, double>{};
  for (final attr in Attribute.values) {
    final rankPct = (denom - ranks[attr]!) / denom;
    final gPct = globalPct[attr]!;
    final blended = _rankWeight * rankPct + _globalWeight * gPct;
    final score = 5.0 + blended * 5.0;
    result[attr] = (score * 10).round() / 10.0;
  }
  return result;
}

/// Single-attribute normalization — used by partial flows (compat engine)
/// that can't run the full 10-attribute rank step.
double normalizeScore(double raw, Attribute attr, Gender gender) {
  final pct = _rawToPercentile(raw, attr, gender);
  final score = 5.0 + pct * 5.0;
  return (score * 10).round() / 10.0;
}
