// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACPS-ZOkxBc4sYtzXc_sO5ryQU50nnl_8',
    appId: '1:298461981552:web:d12764622d211277ecbdb5',
    messagingSenderId: '298461981552',
    projectId: 'ai-face-reader-1960a',
    authDomain: 'ai-face-reader-1960a.firebaseapp.com',
    storageBucket: 'ai-face-reader-1960a.firebasestorage.app',
    measurementId: 'G-LBNXBT0M1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm3rNOht9COTg3zcpHsrNvVlQmfrkibt4',
    appId: '1:298461981552:android:d5333fb0909678acecbdb5',
    messagingSenderId: '298461981552',
    projectId: 'ai-face-reader-1960a',
    storageBucket: 'ai-face-reader-1960a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpf4lTiPzVAg044uG2lJ4ZNolCpjNiPA',
    appId: '1:298461981552:ios:46ad2778bf836e11ecbdb5',
    messagingSenderId: '298461981552',
    projectId: 'ai-face-reader-1960a',
    storageBucket: 'ai-face-reader-1960a.firebasestorage.app',
    iosBundleId: 'com.scienceintegration.face',
  );

}