// Type augmentation for secrets that are not yet visible in
// `worker-configuration.d.ts` (regenerated by `pnpm cf-typegen`).
//
// Once you run `pnpm wrangler secret put <NAME>` for each of these and then
// `pnpm cf-typegen`, the secrets will appear in the auto-generated file and
// this file becomes redundant but harmless (declaration merging).
declare namespace Cloudflare {
  interface Env {
    /** R2 S3-compatible Access Key ID (from R2 → Manage R2 API Tokens). */
    R2_ACCESS_KEY_ID: string;
    /** R2 S3-compatible Secret Access Key — paired with R2_ACCESS_KEY_ID. */
    R2_SECRET_ACCESS_KEY: string;
    /** HMAC secret shared with the Python /analyze service. */
    FACE_API_SECRET: string;
  }
}
